### ISSUE TITLE
EntryPoint must be in 'name=module:attrs

### ISSUE THREAD

**Issue by ferni7** [fg1/exif-revgeo#1]
andrew@ubox2:~/git$ pip install https://github.com/fg1/exif-revgeo/archive/master.tar.gz
Collecting https://github.com/fg1/exif-revgeo/archive/master.tar.gz
  Downloading https://github.com/fg1/exif-revgeo/archive/master.tar.gz
    Complete output from command python setup.py egg_info:
    error in exif-revgeo setup command: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'exif-revgeo=exif-revgeo:cli')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4QV2XN-build/

Quick google suggests the dash in the module name may be causing the issue?

**Comment by fg1** [comment]
Thanks for the notification! It should be working now.
